first_name = input("enter your first name")
m_i = input("enter your middle initial")
last_name = input("enter your last name")
s_a = input("enter street adress")
c_z =  input("enter city and zipcode")
ph_n = input("enter phone number")
Email = input("enter email")
